# Generated by Django 3.2.9 on 2021-12-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='img/default-profile.png', null=True, upload_to='users/pictures'),
        ),
    ]
